#!/usr/bin/env python

import glob
import os
import os.path
import subprocess
import sys

TESTS = [
    "tests/JSONUnit",
    "tests/JSONProperties",
    "tests/JSProperties",
]

def run_tests():
    print "=> COMPILING"
    for test in TESTS:
        exit_if_unsuccessful(["ghc", "--make", "%s.hs" % test])
    print
    print "=> RUNNING"
    for test in TESTS:
        print "==> %s" % test
        exit_if_unsuccessful([test])

def exit_if_unsuccessful(cmd):
    if subprocess.call(cmd) != 0:
        sys.exit(1)

if __name__ == "__main__":
    os.chdir(os.path.join(os.path.dirname(__file__), ".."))
    run_tests()
